# Generated by Django 5.1.4 on 2024-12-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_order_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('La', 'Laptop'), ('Mo', 'Mobile'), ('Tab', 'Tablet'), ('TV', 'TV'), ('Ga', 'Gaming'), ('App', 'Appliance'), ('Ac', 'Accessories')], max_length=5),
        ),
    ]
